name: Build Docker Image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Get short commit sha
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          echo "DOCKER_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Print Docker tag name
        run: |
          echo "${{ env.DOCKER_TAG }}"

      - name: Clone
        uses: actions/checkout@v5
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ablaze-mirai/git-lfs-server-php:${{ env.DOCKER_TAG }}

      - name: Build and push (latest)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ablaze-mirai/git-lfs-server-php:latest
